### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ubnt-intrepid** [ubnt-intrepid/susanoo#1]
## Core Features
- [x] Body parser
  - [x] `text/plain`
  - [x] `application/x-www-form-urlencoded`
  - [x] `application/json`
- [ ] Configuration file (>= 0.2)
- [ ] Logging support (#16, >= 0.2)
- [x] Router
  - [x] basic routing
  - [x] use `RegexSet` (#12)
- [x] Custom error handler (#21)
- [ ] Responders
  - [x] redirect
  - [x] static files handling
  - [ ] status code
- [ ] Cookie/Session management
  - [ ] CookieJar
  - [ ] Session storage per request

## Documentation
- [x] README
- [ ] documentation comment
- [ ] getting started

**Comment by ubnt-intrepid** [comment]
### `Middleware::call` の戻り値について
* 例えば静的ファイルを返すミドルウェアの場合，即 `Response` を返したうえで以降の結果を実行したくない
  - `Failure` に `Response` を乗せるのでもよいが，エラーではない場合の扱いが微妙
* `AsyncResult<MiddlewareResult>`
  - `From<Response>` と `From<Context>` を用意しておく

**Comment by ubnt-intrepid** [comment]
## `Chain` の実装
* ミドルウェアを階層的に適用したい場合がある
  - 特定のルートに認証を当てたい場合など

```rust
struct Chain {
  controller: Arc<Controller>,
  middlewares: Vec<Arc<Middleware>>,
}

impl Chain {
  fn add_middleware<M:Middleware>(&mut self, m: M) -> &mut Self { /* ... */ }
}

trait Controller {
  // ...
  fn chained(self) -> Chain {
    Chain { controller: Arc::new(self), middlewares: Vec::new(), }
  }
}
```

### 問題点
* ルータは階層化できない

**Comment by ubnt-intrepid** [comment]
This issue has not maintained anymore and confusing. just closes
