### ISSUE TITLE
Tracking issue for HTTP2/TLS support

### ISSUE THREAD

**Issue by ubnt-intrepid** [ubnt-intrepid/susanoo#103]
### TLS
- [ ] switch to rustls (#102)
- [ ] improve configuration methods

### HTTP/2
- [ ] Waiting for https://github.com/hyperium/hyper/issues/304, or contribute
- [ ] Add support for HTTP/1.1 upgrade (depends on the specification of hyper's API)
- [ ] ALPN
