### ISSUE TITLE
Tracking issue for configuration of Tokio runtime

### ISSUE THREAD

**Issue by ubnt-intrepid** [ubnt-intrepid/susanoo#104]
- [ ] Export the reactor handle `Handle`
- [ ] Remove the handle of executor `TaskExecutor` from `ServiceContext`
   - From futures-0.2, the way will be provided which allows accessing `Executor` from inner of `Future`.
- [ ] Improve error reporting
  - Use embedded logger (log4rs or slog-rs)
